# Generated by Django 3.0 on 2019-12-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('automated_system', '0003_auto_20191206_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='maintainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='automated_system.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
