# Generated by Django 3.0.5 on 2020-04-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('digit_code', models.CharField(blank=True, max_length=9)),
                ('shelf_life', models.DateTimeField(null=True)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('stackable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('sold_count', models.IntegerField(default=0)),
                ('is_stock_day', models.BooleanField(default=False)),
                ('failures_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('P', 'personel'), ('M', 'management'), ('A', 'admin')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('carrying_capacity', models.FloatField(default=0.0)),
                ('shelf_number', models.IntegerField(default=0)),
                ('last_charge', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=0)),
                ('delivery_timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_price', models.FloatField(default=0.0)),
                ('start_timestamp', models.DateTimeField(auto_now=True)),
                ('end_timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system.Product')),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.FloatField(default=0.0)),
                ('sold_date', models.DateTimeField(auto_now=True)),
                ('sold_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('severity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('possible_cause', models.TextField(blank=True)),
                ('possible_solution', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.User')),
            ],
        ),
    ]
