# Generated by Django 3.0.5 on 2020-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='shelf_number',
        ),
        migrations.AddField(
            model_name='store',
            name='section_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='shelf_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
