# Generated by Django 3.0 on 2019-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
