# Generated by Django 3.0.5 on 2020-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0003_auto_20200509_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('P', 'Personel'), ('M', 'Management'), ('A', 'SystemAdministrators')], default='P', max_length=1),
        ),
    ]
