# Generated by Django 3.0 on 2019-12-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0004_auto_20191206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='maintainer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.Staff'),
        ),
    ]
