# Generated by Django 3.0.5 on 2020-05-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0005_auto_20200510_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='revenue',
        ),
        migrations.AddField(
            model_name='statistics',
            name='shelf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='automated_system.Store'),
            preserve_default=False,
        ),
    ]
