# Generated by Django 3.0.5 on 2020-05-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0007_statistics_price_that_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='is_stock_day',
        ),
        migrations.AddField(
            model_name='statistics',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_system.Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_timestamp',
            field=models.DateTimeField(),
        ),
    ]
