# Generated by Django 3.0.5 on 2020-05-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0008_auto_20200523_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shelf',
        ),
    ]
