# Generated by Django 3.0.5 on 2020-05-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0009_auto_20200523_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
