# Generated by Django 3.0.5 on 2020-05-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0011_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='delivery_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
