# Generated by Django 3.0.5 on 2020-05-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system', '0013_auto_20200525_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automated_system.Product'),
        ),
    ]
